language: scala
scala: 2.11.2

addons:
  firefox: latest

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz"
  - "tar zxf geckodriver-v0.18.0-linux64.tar.gz"
  - sleep 3 # give xvfb some time to start

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dwebdriver.gecko.driver=geckodriver test

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  branch: md5deep
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
    - "$HOME/.sbt/launchers/"
    - "$HOME/.coursier"

env:
  global:
  - secure: "I9K7uwpiLcC0B3s98pfysd0kSnsTOzKGuwEmFcUAqJiKuEfjPRJ1ervq2G9BbNoiPA3NgVJZkPvl5LtNLcDDXH+qdg+p091la6NoUeoQfbN+J/AKHNXW9J97E65bJZaxIwX6CeZsRb9nAGm6frp6MY1Ph2F04jMEqIAy5NVLIvMyuAYSvdj3W5ZZ7TRcNeOMDiU0rZVYeJbsFSYHPbGizPF5iTQLqWHqyLSW2W51V62yUP1PmlEqyIqpqB+JkuxBG5kKNuX/6HDHRUpQQMn1Ub+GTegFB244NUGGV6nEpEqBtoifVOk6AC/ciVR72KogoHrEAfo38CSIT2uwolOkzSyyUpS8d4H3jCMOxpHxrwyReBrAG+kr6Y96DvrN1pLuUSIbA5QZ3DVvCb8CcrfeRiY6rSPx5A5EdMoz/iRNliAHIMuoSQtzmNy30H2tdLG2+y/6bvvK4eY/mnL1C9SJx/+lmwZgPsCkZ+zXMPxpttnzuFm0rxcTV6uq7hTJh7MBZ097iGgdAgQj8QNVZi8ZJmYsQZs2/GHTw+ayEwGW1cbrL/IjtdBqVRT0bu1z8xcbPeU7heSUm4+8qCKtC0HeEX0HseDjQBdR6SqJGGRlaMVSFxtv71kVr8tDo1LKQ7FnieH7PuGo2Rb3dxuGKM7Wk4ziXpBOO7sWp+vYHOXBSfw="
  - secure:  "PEg9RWSTjecznZ2wgXdlfF1OHaIfKZSwi+GUug+o4gF3KRDqQK8pZmC3nxCLyD3ATXHPQWsTTqIwi1UkyITmM7JeRkDKace6uykg/Uz94Zwl5Xhah7F0pjBi7YjAGWby28RU9zvILOEeV+K9USnAl8ZVA4/Q8vD9eMXmwppNhL+MbOhBo7Xm2glGoIwGTB1gVGiiX7q20odxTSFD61F5CVZJpS+756odAuV80My6GEsBrROj2m8Cmy12+R5KQL9Iy33Hb2Oo6g17wRQfzKn4XFtNvO4B9BJ/M5kjBSlXEkLgqffCYtOZpv0eOpwpqKQFl6m4ENLfmh3PSYT8N2gbc1FaoGDFOs8SpGuFmIyIMXVLwXZjgN9OR1dVhqqkwwmkJq+CCiv1gH3my+0xaFlTvwjm5jnsBQqSnaR1tlQ9mFD42B4s4WVQT/juz94ToQRWZCbgi96KXQONlCkYiNEgGanyOk4Dm1Cgp5gBmvh0pnOj6O3PM/2VxK96sp6Lu/ayjCVZQ1qBAgQJNEaV+tktWrz6rbezqgp/MIhc1yBPgeEZI3gRafLCQCjl3Z/JQeYtkvY87mNkvr2r371MtMbn1hM9jO19I1js7mNVP4JGq98f9klSB7e5QmkPUraE/DzNQ6hAAqnyMY5zwAEuPiOON0Q7/+ovwC1t4oxRJLG4zXA="
