language: scala
scala: 2.11.2

addons:
  firefox: latest

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz"
  - "tar zxf geckodriver-v0.18.0-linux64.tar.gz"
  - sleep 3 # give xvfb some time to start

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dwebdriver.gecko.driver=geckodriver test

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  branch: md5deep
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
    - "$HOME/.sbt/launchers/"
    - "$HOME/.coursier"

env:
  global:
  - secure: "I9K7uwpiLcC0B3s98pfysd0kSnsTOzKGuwEmFcUAqJiKuEfjPRJ1ervq2G9BbNoiPA3NgVJZkPvl5LtNLcDDXH+qdg+p091la6NoUeoQfbN+J/AKHNXW9J97E65bJZaxIwX6CeZsRb9nAGm6frp6MY1Ph2F04jMEqIAy5NVLIvMyuAYSvdj3W5ZZ7TRcNeOMDiU0rZVYeJbsFSYHPbGizPF5iTQLqWHqyLSW2W51V62yUP1PmlEqyIqpqB+JkuxBG5kKNuX/6HDHRUpQQMn1Ub+GTegFB244NUGGV6nEpEqBtoifVOk6AC/ciVR72KogoHrEAfo38CSIT2uwolOkzSyyUpS8d4H3jCMOxpHxrwyReBrAG+kr6Y96DvrN1pLuUSIbA5QZ3DVvCb8CcrfeRiY6rSPx5A5EdMoz/iRNliAHIMuoSQtzmNy30H2tdLG2+y/6bvvK4eY/mnL1C9SJx/+lmwZgPsCkZ+zXMPxpttnzuFm0rxcTV6uq7hTJh7MBZ097iGgdAgQj8QNVZi8ZJmYsQZs2/GHTw+ayEwGW1cbrL/IjtdBqVRT0bu1z8xcbPeU7heSUm4+8qCKtC0HeEX0HseDjQBdR6SqJGGRlaMVSFxtv71kVr8tDo1LKQ7FnieH7PuGo2Rb3dxuGKM7Wk4ziXpBOO7sWp+vYHOXBSfw="
  - secure: "cKiCKIkPDi3UqIruMevUqQljRSBnm3p9/ti1SU+WbJwSmjuKYKA2FcYly2ODvJcEQnS1diDRcrAY7bN41OMQ+ZOsJz5VHsWtI5ZpQVH4W6JuUjj8E+44dbddcDJgz7AxJs0EWHROV6JvPWk/HzW5BBPkXeB9M0Q5qkf4BBTX/t+TvYMOlpTux5s+9E+rFp4aZXLxk8qzImx6aV7DQmKr8lSp6yNXcx6rhOcpYYK7D6b/kMYD4yV2lyzw3OyY0BKPUYQCh2gednki4Lp3578WfoAYwkM8CogutL6rz0+4f6sxWfHeMLKYrM5QuX2L4pb1gmfxwRBAsMrkbjN3V8j31ypWy+KYgfugvaP9SXxeZmGtrZG0zp4XfjSMiS34nNhcuNK5aeCey66bkrJCfVq0wqyi3UVqP1EkoBMuL2hGvmcpys9MflPcSVRZgAEewssLdew7q4FqhDXjj5jGvhyawyMmRJLEpcjKXgv/YPyzaSZ3Ipf8DfvGUZ24etfjuZcWaPsYj0qxq7A+4CNm5t7gDA0oKuPHvTu7KsGyX/oJGKAprVx0RRbB5dyJGpNSCAtJjx8rGCAljRo2f7pu0ffB+M9AiCne2D6+mBLUvRIFjH4pqOWD/IpD5tAiK0AM3YopwyBsgjRQx9urpiNY6jhdImTYw32jc+eM/B+RID/V9IU="
